material_3C/api/urls.py
from django.urls import path

from api import views

app_name = "api"

urlpatterns = [

]

material_3C/cdplaest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('core/', include("core.urls")),
    path('', include("home.urls")),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

material_3C/core/urls.py
from django.urls import path

from core import views

from .models import *
from .views import *

app_name = "core"
urlpatterns = [
    
    # URL para el listado general
    path('administracion/', listado_general, name='administracion'),
    
    
##Clientes
path('list/clientes/', views.ListClientes.as_view(), name="List_Clientes"),
path('create/cliente/', views.createCliente.as_view(), name="createCliente"),
path('detail/cliente/<int:pk>/', views.DetailClientes.as_view(), name="detailCliente"),
path('update/cliente/<int:pk>/', views.UpdateCliente.as_view(), name="updateCliente"),
path('delete/cliente/<int:pk>/', views.DeleteCliente.as_view(), name="deleteCliente"),

##Tipos
path('list/tipos/', views.ListTipo.as_view(), name="list_tipos"),
path('create/tipo/', views.CreateTipo.as_view(), name="create_tipo"),
path('detail/tipo/<int:pk>/', views.DetailTipo.as_view(), name="detail_tipo"),
path('update/tipo/<int:pk>/', views.UpdateTipo.as_view(), name="update_tipo"),
path('delete/tipo/<int:pk>/', views.DeleteTipo.as_view(), name="delete_tipo"),

##Lugar
path('list/lugar/', views.ListLugar.as_view(), name="listLugar"),
path('create/lugar/', views.CreateLugar.as_view(), name="create_lugar"),
path('detail/lugar/<int:pk>/', views.DetailLugar.as_view(), name="detail_lugar"),
path('update/lugar/<int:pk>/', views.UpdateLugar.as_view(), name="update_lugar"),
path('delete/lugar/<int:pk>/', views.DeleteLugar.as_view(), name="delete_lugar"),

##Catalogo
path('catalogo/', views.Catalogo.as_view(), name="Catalogo"),
    path('agregar_material/<int:pk>/', views.agregar_material.as_view(), name='agregar_material'),
    path('eliminar_material/<int:pk>/', views.eliminar_material.as_view(), name='eliminar_material'),
    path('restar_material/<int:pk>/', views.restar_material.as_view(), name='restar_material'),
    path('limpiar_carrito/', views.limpiar_carrito.as_view(), name='limpiar_carrito'),
    path('confirmar/pedido/', views.CreatePedidoCarro.as_view(), name="pedido_creo"),


    

##Material
path('list/Material/', views.ListMaterial.as_view(), name="list_Mat"),
path('create/Material/', views.CreateMaterial.as_view(), name="create_Mat"),
path('detail/Material/<int:pk>/', views.DetailMaterial.as_view(), name="detail_Mat"),
path('update/Material/<int:pk>/', views.UpdateMaterial.as_view(), name="update_Mat"),
path('delete/Material/<int:pk>/', views.DeleteMaterial.as_view(), name="delete_Mat"),

##Pedido

path('list/pedido/', views.ListPedido.as_view(), name="list_pedido"),
# path('create/pedido/', views.CreatePedido.as_view(), name="create_pedido"),
path('detail/pedido/<int:pk>/', views.DetailPedido.as_view(), name="detail_pedido"),
path('update/pedido/<int:pk>/', views.UpdatePedido.as_view(), name="update_pedido"),
path('delete/pedido/<int:pk>/', views.DeletePedido.as_view(), name="delete_pedido"),


##Almacen

path('list/almacen/', views.ListAlmacenes.as_view(), name="list_almacen"),
path('create/almacen/', views.CreateAlmacen.as_view(), name="create_almacen"),
path('detail/almacen/<int:pk>/', views.DetailAlmacen.as_view(), name="detail_almacen"),
path('update/almacen/<int:pk>/', views.UpdateAlmacen.as_view(), name="update_almacen"),
path('delete/almacen/<int:pk>/', views.DeleteAlmacen.as_view(), name="delete_almacen"),


##Resenas

path('list/resenas/', views.Listresenas.as_view(), name="list_resena"),
path('create/resenas/', views.Createresenas.as_view(), name="create_resena"),
path('detail/resenas/<int:pk>/', views.Detailresenas.as_view(), name="detail_resena"),
path('update/resenas/<int:pk>/', views.Updateresenas.as_view(), name="update_resena"),
path('delete/resenas/<int:pk>/', views.Deleteresenas.as_view(), name="delete_resena"),

##Pagos

path('list/pagos/', views.ListPago.as_view(), name="list_Pago"),
path('create/pagos/', views.CreatePago.as_view(), name="create_Pago"),
path('detail/pagos/<int:pk>/', views.DetailPago.as_view(), name="detail_Pago"),
path('update/pagos/<int:pk>/', views.UpdatePago.as_view(), name="update_Pago"),
path('delete/pagos/<int:pk>/', views.DeletePago.as_view(), name="delete_Pago"),

##Cambios

# path('list/cambios/', views.ListCambios.as_view(), name="list_cambio"),
# path('create/cambios/', views.CreateCambios.as_view(), name="create_cambio"),
# path('detail/cambios/<int:pk>/', views.DetailCambios.as_view(), name="detail_cambio"),
# path('update/cambios/<int:pk>/', views.UpdateCambios.as_view(), name="update_cambio"),
# path('delete/cambios/<int:pk>/', views.DeleteCambios.as_view(), name="delete_cambio"),


##Proveedor
path('list/Proveedor/', views.ListProveedor.as_view(), name="List_Proveedor"),
path('create/Proveedor/', views.createProveedor.as_view(), name="createProveedor"),
path('detail/Proveedor/<int:pk>/', views.DetailProveedor.as_view(), name="detailProveedor"),
path('update/Proveedor/<int:pk>/', views.UpdateProveedor.as_view(), name="updateProveedor"),
path('delete/Proveedor/<int:pk>/', views.DeleteProveedor.as_view(), name="deleteProveedor"),



##Compra

path('list/compra/', views.ListCompra.as_view(), name="list_compra"),
path('create/compra/', views.CreateCompra.as_view(), name="create_compra"),
path('detail/compra/<int:pk>/', views.DetailCompra.as_view(), name="detail_compra"),
path('update/compra/<int:pk>/', views.UpdateCompra.as_view(), name="update_compra"),
path('delete/compra/<int:pk>/', views.DeleteCompra.as_view(), name="delete_compra"),





]

material_3C/home/urls.py
from django.urls import path

from home import views

app_name = "home"

urlpatterns = [
        path('', views.Index.as_view(), name="index"),
        path('about/', views.About.as_view(), name="about"),
        path('identity', views.Identity.as_view(), name="identity"),
        path('contacto', views.Contacto.as_view(), name="contacto"),
        path('signup/', views.SignUp.as_view(), name="signup"),
        path('logout/', views.LogOut.as_view(), name="logout"),
        path('login/', views.LogIn.as_view(), name="login"),
        
        
    
    ]

material_3C/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{%block tittle %}{%endblock tittle %}</title>
  <link rel="stylesheet" href="{% static 'css/boosted.min.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">


  <!-- <script src="{% static 'js/jquery-3.6.2.min.js' %}"></script> -->

  <!-- <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/boostrap/min.css' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script> -->





  <!-- <script src="https://code.jquery.com/jquery-3.6.2.min.js"></script> -->
  <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script> -->
  <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script> -->







</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg" style="background-color: darkorange;">
      <div class="container">
        <a class="navbar-brand" href="#">MC</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-auto">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home:index' %}" style="color: white;">Inicio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:Catalogo' %}" style="color: white;">Catalogo</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:contacto' %}" style="color: white;">Contacto</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:about' %}" style="color: white;">Sobre Nosotros</a>
            </li>

            <li class="nav-item">
              {% if request.user.is_authenticated %}
              <a class="nav-link" href="{% url 'core:administracion' %}" style="color: white;">Administración</a>
              {% else %}
    
              {% endif %}
            </li>
          </ul>
          <ul></ul>
          <ul></ul>
          <ul></ul>
          <ul></ul>
          <ul></ul>
          <ul></ul>
          <!-- Nuevo div para iniciar sesión o registrarse -->
          <div class="d-flex">
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                {% if request.user.is_authenticated %}
                <a class="nav-link" href="{% url 'home:logout' %}" style="color: white;">Cerrar Sesión</a>
                {% else %}
                <a class="nav-link" href="{% url 'home:login' %}" style="color: white;">Iniciar Sesión</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home:signup' %}" style="color: white;">Registrarse</a>
              </li>
              {% endif %}
            </ul>
          </div>
    
        </div>
      </div>
    </nav>
    
  </header>
  <div class="container-fluid">
    <div class="row">
      <div class="col">

      </div>
      <div>
        {% comment %} <div class="col -18"> {% endcomment %}
          {%block content %}

          {%endblock content %}

          <br>
        </div>



      </div>

    </div>


  </div>



  <!-- Remove the container if you want to extend the Footer to full width. -->
  <!-- {% comment %} <div class="container my-5"> {% endcomment %} -->
  <div class="my-18 ">

    <footer class="bg-dark text-light text-center py-3">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <h5>Contacto</h5>
            <p>Carretera Libre Tijuana-Tecate Km 10 Fracc. El Refugio, Quintas Campestre, 22253 Redondo, B.C.</p>
            <p>Email: info@elconstructor.com</p>
            <p>Teléfono: +52 664 800 0096</p>
          </div>
          <div class="col-md-6">
            <h5>Síguenos</h5>
            <a href="#" class="text-light me-2"><i class="bi bi-facebook"></i></a>
            <a href="#" class="text-light me-2"><i class="bi bi-twitter"></i></a>
            <a href="#" class="text-light me-2"><i class="bi bi-instagram"></i></a>
          </div>
        </div>
        <div class="mt-3">
          <p>&copy; 2023 MATERIALES DE CONSTRUCCION</p>
        </div>
      </div>
    </footer>
  </div>
  {% comment %} </div> {% endcomment %}
  <!-- End of .container -->





  <script src="{% static 'js/jquery-3.6.2.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/boosted.min.js' %}"></script>
  <script src="{% static 'js/bootstrap/min.css' %}"></script>



</body>


</html>

<!-- Con los {%load static %} que estan en el archivo los paso pa todos, es herencia -->